### ISSUE TITLE
Consider redirecting users to elado/rollup-plugin-preserve-shebangs

### ISSUE THREAD

**Issue by maranomynet** [developit/rollup-plugin-preserve-shebang#12]
Hi @developit 
As it seems this plugin has long gone dormant, and triggers loud warnings in newer versions of Rollup and doesn't work with input maps, have you considered issuing a formal recommendation for users to use something like
https://github.com/elado/rollup-plugin-preserve-shebangs instead.

**Comment by developit** [comment]
Apologies for letting this plugin rot! We stopped using it in Microbundle when it broke, and I never got around to fixing it here. 

I've just published a new [1.0.0](https://github.com/developit/rollup-plugin-preserve-shebang/releases/tag/1.0.0) that addresses all open issues.
