### ISSUE TITLE
The transformBundle hook used by plugin preserve-shebang is deprecated.

### ISSUE THREAD

**Issue by mirismaili** [developit/rollup-plugin-preserve-shebang#9]
Thanks. But seems to be a need for correction(s). When I adding this plugin to the list of rollup plugins, then I receive this warning message during build process:

> **(!) preserve-shebang plugin: The transformBundle hook used by plugin preserve-shebang is deprecated. The renderChunk hook should be used instead.**

**Comment by anlia260** [comment]
still useless

**Comment by andrewmclagan** [comment]
What is still useless?

**Comment by hugmanrique** [comment]
#8 fixes this problem (thanks jaredpalmer!)

**Comment by developit** [comment]
Apologies for the super slow merge.
